name: VulnAlerts

on: 
  push:
     branches: [ master ]
    
jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
    - name: Build Docker Image
      run: docker system prune --all --force
    - uses: actions/checkout@master
    - uses: y-mehta/vulnalerts@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: done
      run: echo 'done'
